# Generated by Django 5.1.3 on 2024-11-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
